# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yingkezhibo-OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yingkezhibo-OC

  target 'yingkezhibo-OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yingkezhibo-OCUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYKit'
pod 'MJExtension'
pod 'LFLiveKit'
end
